// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: rpc/irpc/irpc.proto

package irpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type IrpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *IrpcRequest) Reset() {
	*x = IrpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_irpc_irpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrpcRequest) ProtoMessage() {}

func (x *IrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_irpc_irpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrpcRequest.ProtoReflect.Descriptor instead.
func (*IrpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_irpc_irpc_proto_rawDescGZIP(), []int{0}
}

func (x *IrpcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type IrpcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IrpcReply) Reset() {
	*x = IrpcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_irpc_irpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrpcReply) ProtoMessage() {}

func (x *IrpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_irpc_irpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrpcReply.ProtoReflect.Descriptor instead.
func (*IrpcReply) Descriptor() ([]byte, []int) {
	return file_rpc_irpc_irpc_proto_rawDescGZIP(), []int{1}
}

func (x *IrpcReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_irpc_irpc_proto protoreflect.FileDescriptor

var file_rpc_irpc_irpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x72, 0x70, 0x63, 0x22, 0x21, 0x0a, 0x0b, 0x49,
	0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25,
	0x0a, 0x09, 0x49, 0x72, 0x70, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x40, 0x0a, 0x0b, 0x49, 0x72, 0x70, 0x63, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x49, 0x72, 0x70, 0x63, 0x47, 0x72, 0x65, 0x65,
	0x74, 0x12, 0x11, 0x2e, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x72, 0x70, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x72, 0x70, 0x63,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x69, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_irpc_irpc_proto_rawDescOnce sync.Once
	file_rpc_irpc_irpc_proto_rawDescData = file_rpc_irpc_irpc_proto_rawDesc
)

func file_rpc_irpc_irpc_proto_rawDescGZIP() []byte {
	file_rpc_irpc_irpc_proto_rawDescOnce.Do(func() {
		file_rpc_irpc_irpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_irpc_irpc_proto_rawDescData)
	})
	return file_rpc_irpc_irpc_proto_rawDescData
}

var file_rpc_irpc_irpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_irpc_irpc_proto_goTypes = []interface{}{
	(*IrpcRequest)(nil), // 0: irpc.IrpcRequest
	(*IrpcReply)(nil),   // 1: irpc.IrpcReply
}
var file_rpc_irpc_irpc_proto_depIdxs = []int32{
	0, // 0: irpc.IrpcGreeter.IrpcGreet:input_type -> irpc.IrpcRequest
	1, // 1: irpc.IrpcGreeter.IrpcGreet:output_type -> irpc.IrpcReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_irpc_irpc_proto_init() }
func file_rpc_irpc_irpc_proto_init() {
	if File_rpc_irpc_irpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_irpc_irpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_irpc_irpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrpcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_irpc_irpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_irpc_irpc_proto_goTypes,
		DependencyIndexes: file_rpc_irpc_irpc_proto_depIdxs,
		MessageInfos:      file_rpc_irpc_irpc_proto_msgTypes,
	}.Build()
	File_rpc_irpc_irpc_proto = out.File
	file_rpc_irpc_irpc_proto_rawDesc = nil
	file_rpc_irpc_irpc_proto_goTypes = nil
	file_rpc_irpc_irpc_proto_depIdxs = nil
}
